global_user = "root"
global_key = "~/.ssh/id_rsa"
#global_password = "test"

[[projects]]
name = "default"
src = "~/Desktop/default/"
dest = "~/default/"
exclude = [
            ".git",
            ".idea",
            ".vscode",
            "test",
        ]

[[projects]]
name = "test"
src = "~/Desktop/test/"
dest = "~/test/"
exclude = [
            ".git",
            ".idea",
            ".vscode",
        ]
