global_user = "root"
#global_key = "~/.ssh/id_rsa"
global_password = "root"

[[projects]]
name = "default"
src = "~/Desktop/test/"
dest = "~/test/"
exclude = [
            ".git",
            ".idea",
            ".vscode",
        ]
